name: CI Básico + Deploy S3

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # -------- BACKEND --------
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build Back
      run: |
        cd back
        mvn clean package

    # -------- FRONTEND --------
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Build Front
      run: |
        cd front
        npm install
        npm run build

    # -------- AWS --------
    - name: Configurar AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # -------- DEPLOY --------
    - name: Subir a S3
      run: |
        aws s3 sync frontend/dist s3://${{ secrets.S3_BUCKET }} --delete
